WeatherApp/Models/ContactUsModel.cs
namespace WeatherApp.Models
{
    public class ContactUsModel
    {
        //Constructor
        public ContactUsModel()
        {
        }

        //Fields
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Feedback { get; set; }

        public string Message { get; set; }
    }
}

WeatherApp/Models/ErrorViewModel.cs
using System;

namespace WeatherApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WeatherApp/Models/LoginModel.cs
namespace WeatherApp.Models
{
    public class LoginModel
    {
        public string Email { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }

        public string Message { get; set; }
    }
}

WeatherApp/Models/RegisterModel.cs
namespace WeatherApp.Models
{
    public class RegisterModel
    {
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }

        public string Message { get; set; }


    }
}

WeatherApp/Models/WeatherModel.cs
namespace WeatherApp.Models
{
    public class WeatherModel
    {
        public string Country { get; set; }
        public string city { get; set; }
        public string Timezone_id { get; set; }
        public string Woeid { get; set; }

        public string temperature { get; set; }
        public string atmosphere { get; set; }
        public string condition { get; set; }
        
    }
}

WeatherApp/Controllers/ContactUsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using WeatherApp.Models;

namespace WeatherApp.Controllers
{
    public class ContactUsController : Controller
    {

        private readonly IContactUsRepository _contactRepo;


        public ContactUsController(IContactUsRepository contactRepo)
        {
            _contactRepo = contactRepo;
        }


        public IActionResult ContactUs()
        {
            var viewModel = new ContactUsModel();
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> InsertContactUsToDatabase(ContactUsModel contactToInsert)
        {
            //Validate Model
            if (!ModelState.IsValid)
            {
                return View("ContactUs", contactToInsert);
            }

            var viewModel = new ContactUsModel();

            //Check database row insertion
            int rows = await _contactRepo.InsertContactAsync(contactToInsert);
            if (rows > 0)
            {

                viewModel.Message = "Success";
                ModelState.Clear();

            }
            else
            {
                viewModel.Message = "Error";
                ModelState.Clear();
            }

            return View("ContactUs", viewModel);
        }
    }
}

WeatherApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using WeatherApp.Models;

namespace WeatherApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            var viewModel = new WeatherModel();
            return View(viewModel);
        }

        
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WeatherApp/Controllers/UserController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using WeatherApp.Models;

namespace WeatherApp.Controllers
{
    public class UserController : Controller
    {

        private readonly IRegisterRepository _regRepo;
        private readonly ILoginRepository _loginRepo;


        public UserController(IRegisterRepository regRepo, ILoginRepository loginRepo)
        {
            _regRepo = regRepo;
            _loginRepo = loginRepo;
        }


        //-----------  Register  ---------------------//

        public IActionResult Register()
        {
            var viewModel = new RegisterModel();
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> InsertUserToDatabaseAsync(RegisterModel userToInsert)
        {

            //Validate model
            if (!ModelState.IsValid)
            {
                return View("Register", userToInsert);
            }

            var viewModel = new RegisterModel();

            //Check database row insertion
            int rows = await _regRepo.InsertUserAsync(userToInsert);
            if (rows > 0)
            {
                viewModel.Message = "Success";
                ModelState.Clear();
            }
            else
            {
                viewModel.Message = "Error";
                ModelState.Clear();
            }
            return View("Register", viewModel);
        }


        //-------------- Login ---------------------//

        public IActionResult Login()
        {
            var viewModel = new LoginModel();
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> AuthorizationAsync(LoginModel auth)
        {
            //Validate model
            if (!ModelState.IsValid)
            {
                return View("Login", auth);
            }

            var viewModel = new LoginModel();

            //Login succesful
            LoginModel usr = await _loginRepo.GetUserAsync(auth.Email, auth.Password);
            if (usr != null)
            {
                HttpContext.Session.SetString("LoginName", usr.FirstName);
                return RedirectToAction("Index", "Home");
            }

            //Login failed
            else
            {
                viewModel.Message = "Error";
                ModelState.Clear();
                return View("Login", auth);
            }
        }


        //---------------------Logout--------------------//

        public IActionResult Logout()
        {
            HttpContext.Session.Remove("LoginName");
            return RedirectToAction("Index", "Home");
        }
    }
}

WeatherApp/Controllers/WeatherController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using WeatherApp.Models;

namespace WeatherApp.Controllers
{
    public class WeatherController : Controller
    {
        private readonly IWeatherRepository _weatherRepo;

        public WeatherController(IWeatherRepository weatherRepo)
        {
            _weatherRepo = weatherRepo;
        }


        [HttpGet]
        public async Task<IActionResult> ViewWeatherAsync(string country)
        {
            ViewBag.Search = country;
            var weather = await _weatherRepo.GetWeatherAsync(country);
      
            if (weather.Country == null)
            {
                ViewBag.Error = "Error";
                return View("../Home/Index");
            }

            return View(weather);
        }
    }
}

WeatherApp/Views/ContactUs/ContactUs.cshtml
@model ContactUsModel


<link href="~/css/forms.css" rel="stylesheet" />

<!------------------------ContactUs--------------->

<div class="content form_inner">
    <div class="container">
        <div class="card form_bg">
            <div class="card_title">
                <h1 style="color:whitesmoke;">Contact Us</h1>
            </div>
            <div class="form">

                @using (Html.BeginForm("InsertContactUsToDatabase", "ContactUs", "Post"))
                {

                    <input type="text" name="FullName" id="FName" asp-for="FullName" placeholder="Full Name" />
                    <span asp-validation-for="FullName" class="text-danger"></span>
                    <input type="text" name="Email" placeholder="Email" id="email" asp-for="Email" />
                    <span class="text-danger" asp-validation-for="Email"></span>
                    <input name="Feedback" placeholder="Feedback" id="Feedback" asp-for="Feedback" style="height: 95px;">
                    <span asp-validation-for="Feedback" class="text-danger"></span>

                    <input type="submit" style="background-color:dodgerblue;color:white;" value="Submit" />

                    
                    @if (Model.Message == "Success")
                    {
                        <p style="color: green; font-size:medium;font-weight:bold">Message sent successfully!</p>
                    }


                    @if (Model.Message == "Error")
                    {
                        <p style="color: red; font-size:medium;font-weight:bold">Feedback not sent, please try again.</p>
                    }
                }

            </div>
        </div>
    </div>
</div>

WeatherApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<link href="~/css/site.css" rel="stylesheet" />

<!----------------Search-bar--------------->


<div class="content form_inner">
    <div class="search">
        <h1>Search weather</h1>
        <form method="get" enctype="multipart/form-data" class="form validate" asp-controller="Weather" asp-action="ViewWeather">
            <div style="width: 100%; height: 3em;">
                <input type="search" name="country" id="country" value="@ViewBag.Search" placeholder="e.g. Sunnyvale,CA" class="search-field" required />

                @if (ViewBag.Error != null)
                {

                    <label id="country-error" class="error" for="country" style="">Location not found,please try again.</label>
                }
            </div>
            <button type="submit" class="search-button" style="height:3em;">
                <img src="~/images//search.png">
            </button>
        </form>
    </div>
    <br />
</div>

WeatherApp/Views/Home/Register.cshtml
<link href="~/css/forms.css" rel="stylesheet" />

<div class="content form_inner">
    <div class="container">
        <div class="card form_bg">
            <div class="card_title">
                <h1 style="color:whitesmoke;">Create Account</h1>
                <p><span class="redirect">Already have an account? <a href="Login">Sign In</a></span><p>
            </div>
            <div class="form">
                <form>
                    <input type="text" name="FirstName" id="FName" placeholder="First Name" required />
                    <input type="text" name="LastName" id="LName" placeholder="Last Name" required />
                    <input type="email" name="Email" placeholder="Email" id="email" required />
                    <input type="password" name="Password" placeholder="Password" id="password" required />
                    <input type="password" name="Confirm Password" placeholder="Confirm Password" id="confirmpassword" required />
                    <input type="submit" style="background-color:dodgerblue;color:white;" value="Sign Up" />
                    @*<p style="color: green; font-size:medium;font-weight:bold">Account created successfully</p>*@
                </form>
            </div>
        </div>
    </div>
</div>

WeatherApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WeatherApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>


<!------------Logo, navigation, background image --------------->

<body>
    @{
        //Time conditional background image
        DateTime currentTime = DateTime.Now;
        var background = currentTime.Hour < 21 ? "day-image" : "night-image";

    }

    <header class="@background">
        <nav class="navbar navbar-expand-lg navbar-dark">
            <div class="container">
                <div class="logo">
                    <a class="navbar-brand" href="@Url.Action("Index", "Home")"><img src="~/images//logo.png"></a>
                </div>
                <button type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler">
                    <span class="navbar-toggler-icon"></span>
                </button>



                <div id="navbarSupportedContent" class="collapse navbar-collapse">
                    <ul class="navbar-nav ml-auto">

                        
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white " asp-area="" asp-controller="ContactUs" asp-action="ContactUs">ContactUs</a>
                        </li>

                        @{
                            var loginName = HttpContextAccessor.HttpContext.Session.GetString("LoginName") as string;
                        }


                        @if (!string.IsNullOrEmpty(loginName))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white " asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hi, @loginName !</a>
                            </li>
                        }

                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white " asp-area="" asp-controller="User" asp-action="Login">Login</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-white " asp-area="" asp-controller="User" asp-action="Register">Signup</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-----------Footer Section --------------->
    <footer class="border-top footer text-muted">
        <div class="">
            &copy; 2022 - WeatherApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WeatherApp/Views/User/Login.cshtml
@model LoginModel
<link href="~/css/forms.css" rel="stylesheet" />


<!------------ Login --------------->

<div class="content form_inner">
    <div class="container">
        <div class="card form_bg">
            <div class="card_title">
                <h1 style="color:white;">Login</h1>
                <p><span class="redirect">Don't have an account? <a href="Register">Sign Up</a></span><p>
            </div>
            <div class="form">
                @using (Html.BeginForm("Authorization", "User", "Post"))
                {
                    
                    <input type="text" name="Email" placeholder="Email" id="email" asp-for="Email" />
                    <span class="text-danger" asp-validation-for="Email"></span>


                    <input type="password" name="Password" placeholder="Password" id="password" />
                    <span class="text-danger" asp-validation-for="Password"></span>

                    <input type="submit" style="background-color:dodgerblue;color:white;" value="Login" />

                    @if (Model.Message == "Error")
                    {
                        <p style="color: red; font-size:medium;font-weight:bold">Incorrect Username or Password.</p>
                    }
                }
            </div>
        </div>
    </div>
</div>

WeatherApp/Views/User/Register.cshtml
@model RegisterModel
<link href="~/css/forms.css" rel="stylesheet" />


<!--------------- Register-------------->

<div class="content form_inner">
    <div class="container">
        <div class="card form_bg">
            <div class="card_title">
                <h1 style="color:whitesmoke;">Create Account</h1>
                <p><span class="redirect">Already have an account? <a href="Login">Sign In</a></span><p>
            </div>
            <div class="form">

                @using (Html.BeginForm("InsertUserToDatabase", "User", "Post"))
                {

                    <input type="text" name="FirstName" id="FName" asp-for="FirstName" placeholder="First Name" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>

                    <input type="text" name="LastName" id="LName" placeholder="Last Name" asp-for="LastName" />
                    <span asp-validation-for="LastName" class="text-danger"></span>

                    <input type="text" name="Email" placeholder="Email" id="email" asp-for="Email" />
                    <span class="text-danger" asp-validation-for="Email"></span>

                    <input type="password" name="Password" placeholder="Password" id="password" />
                    <span class="text-danger" asp-validation-for="Password"></span>

                    <input type="password" name="ConfirmPassword" placeholder="Confirm Password" id="confirmpassword" />
                    <span class="text-danger" asp-validation-for="ConfirmPassword"></span>

                    <input type="submit" style="background-color:dodgerblue;color:white;" value="Sign Up" />

   
                    @if (Model.Message == "Success")
                    {
                        <p style="color: green; font-size: medium; font-weight: bold">Account created successfully!</p>
                    }

                    @if (Model.Message == "Error")
                    {
                        <p style="color: red; font-size:medium;font-weight:bold">Signup failed , please try again.</p>
                    }
                }

            </div>
        </div>
    </div>
</div>

WeatherApp/Views/Weather/Search.cshtml
@model WeatherModel

@{
    ViewData["Title"] = "Home Page";
}


<link href="~/css/weathertable.css" rel="stylesheet" />

<!----- Weather table result ---->
<div class="content" style="top:51%;">

    <table>
        <caption style="font-weight:bold;color:white">Location</caption>
        <tbody>
            <tr>
                <td data-label="Country">@Model.Country</td>
                <td data-label="City">@Model.city</td>
                <td data-label="Region">@Model.Region</td>
                <td data-label="Time Zone">@Model.Timezone_id</td>
            </tr>
        </tbody>
    </table>

    <table>
        <caption style="font-weight:bold;color:white">Current Temperature</caption>
        <tbody>
            <tr>
                <td data-label="Code">@Model.code</td>
                <td data-label="Text">@Model.txt</td>
                <td data-label="Temperature">@Model.temperature</td>
            </tr>
        </tbody>
    </table>
</div>

WeatherApp/Views/Weather/ViewWeather.cshtml
@model WeatherModel

@{
    ViewData["Title"] = "Home Page";
}

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="~/css/weathertable.css" rel="stylesheet" />

<!----- Weather table result ---->

<div class="content" style="top:53%;">

    <table>
        <caption style="font-weight:bold;color:white">Location</caption>
        <tbody>
            <tr>
                <td data-label="Country">@Model.Country</td>
                <td data-label="City">@Model.city</td>
                <td data-label="Time Zone">@Model.Timezone_id</td>
            </tr>
        </tbody>
    </table>

    <table>
        <caption style="font-weight:bold;color:white">Temperature</caption>
        <tbody>
            <tr>
                <td data-label="Temperature">@Model.temperature</td>
                <td data-label="Condition">@Model.condition</td>
                <td data-label="Humidity">@Model.atmosphere</td>
            </tr>
        </tbody>
    </table>
</div>